# compiler/linker flags
CCFLAGS := -std=c99 -Wall -I../../include -I../../lib
LDFLAGS := -lsis8300lib -L../../lib

# files
OBJS := sis8300lib_acq
	
###############################################################################

all: $(OBJS)

clean:
	rm -rf *~ *.o $(OBJS)

sis8300lib_acq:
	gcc $(CCFLAGS) $(LDFLAGS) -o $(OBJS) $(OBJS).c
